### PR TITLE
Feature/328 cleanup postman tests

### PR DESCRIPTION
**Pull request by niraymak**
## Description

It was not possible to run multiple iterations with the Postman tests.
The changes in this pull request makes it possible to run it multiple iterations.

Also some mistakes were fixed. 

Also most of the data created during the run is now deleted at the end of the run.

Still have to look into Roles and RoleScope cleanup and for some reason user 427 and 429 are not deleted yet in the screenshot underneath:
https://gyazo.com/cd8b84e39ba0b893487732972f4d68dd

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I did not update API Controllers, if I did, I added/changed Postman tests
-   [ ] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [x] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

1. Run  backend
2. Clean database. (**Keep institution nr 1 and identityUser admin nr. 2**)
3. Run Postman tests.

## Link to issue

Closes: #328

### CODE REVIEW

**Review by Ruby77 — CHANGES_REQUESTED** [review]
We should not forget to update the wiki 😉

**Review by waltersajtos — APPROVED** [review]
Naming seems a lot clearer now. Tests look good. If the wiki has been changed this is good to go. I will just approve it since Ruben has requested changes for the wiki.

**Comment by niraymak** [comment]
Added performance tab in the Postman guide: https://github.com/DigitalExcellence/dex-backend/wiki/Postman-guide

**Comment by niraymak** [comment]
Also added tabs: Test tab structure and Folder structure in the Postman guide.  
https://github.com/DigitalExcellence/dex-backend/wiki/Postman-guide

**Review by Ruby77 — COMMENTED** [review]
Currently, the average time gets calculated at the end of every iteration. Do you think it's worth to run the tests for multiple iterations? 

Unfortunately, you are not able to calculate the average time after 10 iterations, it has to happen after every iteration. However, when you let it run for multiple iterations, the higher iteration rounds give more reliable 'average times', although you're still stuck with the first iteration which would be less reliable (of course it's a lot better than the old situation).

So what do you think about this?

image

**Review by waltersajtos — CHANGES_REQUESTED** [review]
I think it is good enough for now to run the tests multiple times because the results will get more reliable, as Ruben said. I think it's a good idea to add an extra batch script to run the tests once so developing tests will be easier.

**Review by Ruby77 — APPROVED** [review]
Nice 🎉

**Comment by niraymak** [comment]
Added 2 files for local testing. 1 for 1 iteration and 1 for 3 iterations.

For PR it always runs 3 iterations now. :)

**Review by waltersajtos — APPROVED** [review]
Awesome, thanks for the quick fix!

**Pull request merged**
