### PR TITLE
Bugfix/205 highlight toomuch info

### PR DESCRIPTION
**Pull request by niraymak**
## Description

HighlightResourceResult had a Project field which provided the frontend with too much information. Now it only sends projectId, projectName, highlightDescription and highlightId.

## Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I did not update API Controllers, if I did, I added/changed Postman tests
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [x] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

1. Clone frontend (related branch) and backend.
2. Run postman tests
3. Run frontend and check if highlights on the front page work.

## Link to issue

Closes: #205

### CODE REVIEW

**Review by MeesvanStraten — APPROVED** [review]
Works 💯

**Review by Brend-Smits — DISMISSED** [review]
Update the postman collection and we're good to go

**Review by Brend-Smits — APPROVED** [review]
Awesome!

**Comment by Brend-Smits** [comment]
Since #240 is now merged, make sure the documentation is updated!

**Review by MeesvanStraten — APPROVED** [review]

**Pull request merged**
