### PR TITLE
Added max character length when creating project name 

### PR DESCRIPTION
**Pull request by 1SvenHansen**
Added max length to project name when creating a project (API -> ProjectController -> CreateProjectAsync). Put on 75 for now.

## Description

A few sentences describing the overall goals of the pull request's commits.

## Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [ ] I did not update API Controllers, if I did, I added/changed Postman tests
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
-   [ ] I updated the changelog with an end-user readable description
-   [ ] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

1. Go to the 'Add project manually' modal.
2. Put in a project name longer than 75 characters.
3. Finish all remaining fields and try creating the project on the last wizard screen.
4. Site shows error alert saying "Maximum amount of project name characters exceeded, It is not possible to create a project name with more than 75 characters."

## Link to issue

Closes: #418

### CODE REVIEW

**Review by BartvanEijkelenburg — DISMISSED** [review]

**Comment by MeesvanStraten** [comment]
@1SvenHansen  After some thinking I feel it might be wise to use the validation attributes. Also when updating a project now I still can put in more then 75 characters. I think by using attribute vallidation you only have to declare once instead of checking in every controller method. You could try adding the max length attribute to test it in the project add and update method. Contact me for any questions :).

**Review by MeesvanStraten — CHANGES_REQUESTED** [review]
Read my comment in the conversation. Make sure to handle the update method as well.

**Comment by MeesvanStraten** [comment]
Is this issue now done? If so,  let me know or re request review so I can take a look.

**Comment by 1SvenHansen** [comment]
@MeesvanStraten I'm finishing it now, at the next commit with all checks passed, it can be reviewed.

**Comment by 1SvenHansen** [comment]
@MeesvanStraten It is ready for now. Just getting the 'Registered' roll to succeed the tests when I hardcode the values with specific ones from my database, not getting it to work with the global variables that are being used in the other 'Registered' roll tests.

**Review by MeesvanStraten — APPROVED** [review]

**Review by DaveBouman — APPROVED** [review]
Looks good!

**Pull request merged**
