### PR TITLE
Created code coverage pipeline with report

### PR DESCRIPTION
**Pull request by Yuqera**
## Description

Added a code coverage pipeline to github. It compares the percentage code covered by the tests and creates a report from it, this report will be saved in the artifact of that request.

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ X] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [ X] My code follows the style guidelines of this project
-   [ X] I did not update API Controllers, if I did, I added/changed Postman tests
-   [ X] I have performed a self-review of my own code
-   [ X] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ X] New and existing unit tests pass locally with my changes
-   [ ] I updated the changelog with an end-user readable description
-   [ X] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Create a pull-request
2. Check github actions for the pipeline
3. Click the latest created action
4. Check if the test has passed
5. [Optional] Download the code coverage report

## Link to issue

Closes: #184

### CODE REVIEW

**Comment by Yuqera** [comment]
Nieuwe libraries zijn niet geadd voor een of andere reden. Opnieuw word nu gedaan.

**Comment by Yuqera** [comment]
Alles is gefixt en gefocust op de dex-backend.

**Review by Maxvanhattum — COMMENTED** [review]
Configuration looks fine, but I'm no expert, does it actually do what it's supposed to, is there a demo available or how can I test it?

**Comment by Maxvanhattum** [comment]
I don't understand how this feature is already in the actions tab under code coverage. It seems to me that this pull request is for implementing said feature, however it's already available on the actions tab. How did it get there, doesn't it need to be approved here first @Brend-Smits?
See: https://github.com/DigitalExcellence/dex-backend/actions?query=workflow%3A%22Code+Coverage%22

**Comment by Brend-Smits** [comment]
I've discussed with @Yuqera that we are  going for a slightly different approach: 
- Only execute the action on code push to develop or master
- Create a webpage that shows the results in a user-friendly manner instead of giving them assets (better to show stakeholders as well)
For reference, you can check how we do it in lighthouse checks on the frontend

**Pull request closed without merging**
