### PR TITLE
Feature/395 optimize integration logs

### PR DESCRIPTION
**Pull request by TomiEckert**
## Description

Postman integration tests take up ~60k lines in the logs. That's pretty much unusable if there's an error somewhere in the middle. This PR will shorten it.
Best case scenario would be passing all tests: 1.5k lines (per iteration, we do 3 so result is ~4.5k lines).
Every error gives about 6-10 extra lines, but I didn't want to remove any of these.

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I did not update API Controllers, if I did, I added/changed Postman tests
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [x] I updated the changelog with an end-user readable description
-   [ ] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Do something here...
2. Then run this test...
3. After that, you should see the result here

## Link to issue

Closes: #395

### CODE REVIEW

**Comment by TomiEckert** [comment]
Will want to speed it up as it takes a ridiculous amount of time. Locally I got it up to 1min/iteration so about 3min, I'll have to test it further.
Don't necessarily want a separate PR for that.

**Comment by TomiEckert** [comment]
Well at least it fails faster now

**Comment by TomiEckert** [comment]
I'm pretty confused by this error. Isn't `24Z` should be equal to `240Z`. DateTime handling is wonky somwhere, or it's 24 (twenty four), 240 (two hundred fourty).

```
 1.  AssertionError  Check if updated graduation date matches: 2021-04-03T14:35:12.240Z                 
     iteration: 3    expected '2021-04-03T14:35:12.24Z' to deeply equal '2021-04-03T14:35:12.240Z'      
                     at assertion:2 in test-script                                                      
                     inside "ACL / ConvertRegisteredToAlumni / ChangeExpectedGraduationDate-Registered" 
```

**Comment by TomiEckert** [comment]
This is just gambling at this point... I'd bet anything that if I were to rerun the tests 2 more times, at least one of those would fail.

**Comment by TomiEckert** [comment]
This will shorten the logs to about 5k lines on a successful run, and reduces the time it takes by 2 minutes. It technically should not break anything even with 0ms delay between requests as the backend generally does the appropriate work before sending a response. But 75ms seems stable enough.

**Review by niraymak — COMMENTED** [review]
Nice work! The Postman tests are succeeding way faster aswell :)

Why did you choose for --delay-request=75? And why not 50?
If we add more or different tests, could it fail with 75?

**Comment by niraymak** [comment]
Just tested this with Max. We removed the --delay-request parameter and the total time decreased from about 6m to about 1m20s. 
Apparantly this parameter was not necessary. 

Logs are also decreased by a lot of lines :) Thanks for your effort.

**Comment by niraymak** [comment]
Don't forget to edit the changelog.

**Comment by TomiEckert** [comment]
Currently the test runs 3 times as the `-n 3` option specifies. Could also further decrease the speed and amount of logs by decreasing it. The chances that 1st 2 iterations succeed and the 3rd fails are slim, imo. By decreasing it to 2 we'd get 30s and ~1800 lines less.

https://github.com/DigitalExcellence/dex-backend/blob/2ecae57c74520b29000468b7899b7c15e326568f/.github/workflows/run-tests.yml#L51

**Review by niraymak — APPROVED** [review]
Great first PR! 💯

**Review by RubenFricke — DISMISSED** [review]
Good work, thanks for your pull request. Don't forget to fill in the Steps to Test or Reproduce next time.

**Comment by TomiEckert** [comment]
Rebased to develop and changed the elasticsearch options to match the integration testing

**Review by RubenFricke — APPROVED** [review]
Good work, thanks!

**Review by niraymak — APPROVED** [review]

**Pull request merged**
