### PR TITLE
Feature#438 transfer project ownership

### PR DESCRIPTION
**Pull request by MeesvanStraten**
## Description

Remember, this is a draft PR.
You will need two accounts to test this PR. 1 account to initiate the project transfer from and the second one to take the ownership. You also will need 2 email accounts, So you could use your FHICT email and a personal mail etc.
You can change an email adress of a DeX user in the User table.

Also you will need to set envoirement variables for the sendgrid api key and the dex email account. You will find the name of the variables in the MailClient.cs class and the values you can ask me for or view our pass manager.
Make sure that your two email accounts are present in the database and that it does not show <Redacted> !!

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I did not update API Controllers, if I did, I added/changed Postman tests
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] I updated the changelog with an end-user readable description
-   [ ] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

1. Login as a user and check that you have a project.
2. Via SwaggerUI go to the **/api/Project/transfer/{projectId}** endpoint and enter the email address for the new project owner combined with the projectId. The email adress should belong to a DeX user. You can change the email address in the database. Or more easy use two different FHICT accounts.
3. You should have an email indicating the project transfer. Accept or Deny. Please test all possible outcomes.
4. After accepting the transfer, the new user should also receive an email (this is the email address you entered, this also must be a DeX user!!)
5. After accepting the second email verification the project should now be transferred to the new user.

## Link to issue

Closes: #438

### CODE REVIEW

**Comment by 1SvenHansen** [comment]
@MeesvanStraten I keep getting "Transfer could not be initiated" response. Should we look at it together tomorrow? As I think it's something on my side

**Comment by BartvanEijkelenburg** [comment]
@MeesvanStraten I got the same "transfer could not be initiated" response.

**Comment by MeesvanStraten** [comment]
@1SvenHansen @BartvanEijkelenburg  Yea we can have a look if you have time available. Sent me a message on teams. Maybe we can sit with three at the same time.

**Review by BartvanEijkelenburg — COMMENTED** [review]
Checked it all, Looks good.

One thing what would be great to be added (saw it as a ToDo aswell), to notify the owner when the transfership was declined and notify the owner when the project has been transferd.

When I transfer a project only the accepting user knows whether it was succesfull or not.

**Comment by MeesvanStraten** [comment]
@BartvanEijkelenburg Will add that today yeah.

**Comment by MeesvanStraten** [comment]
@1SvenHansen  @BartvanEijkelenburg  @DaveBouman  I added an email where the succesfull transfer is communicated with both users (old and new). Also I added an email where the current owner is notified when the potential new user denies the request.

**Comment by DaveBouman** [comment]
Look good! But I miss a concrete way to cancel the transfer of a project owner when the old owner has initiated the transfer but the new owner has not yet accepted. What if I change my mind or the new owner does not respond how can I rectract he transfer process after accepting it on my part.

**Review by DaveBouman — APPROVED** [review]

**Review by BartvanEijkelenburg — APPROVED** [review]

**Pull request merged**
