### PR TITLE
Made the get all projects function better

### PR DESCRIPTION
**Pull request by TimSnoek123**
## Description

Updated the get all projects repository function, performance is now improved for:

500 projects: 1600ms to 360ms.
30 projects:  250ms to 165ms
## Type of change

-   [X] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [X] My code follows the style guidelines of this project
-   [ ] I did not update API Controllers, if I did, I added/changed Postman tests
-   [X] I have performed a self-review of my own code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes
-   [X] I updated the changelog with an end-user readable description
-   [X] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

To test just call the Project [HttpGet] endpoint to get all projects

## Link to issue

Closes: #436

### CODE REVIEW

**Comment by Maxvanhattum** [comment]
Hey @TimSnoek123 , I thought @niraymak changed that getall method to those .loads() because he said it improved the performance. Have you and he compared response times of these different ways of retrieving the projects? Maybe you two can talk about this?

**Comment by TimSnoek123** [comment]
I will test that tomorrow, .load() shouldn't improve the response time from what I know about it, but if it does then I will add that part back. Still the time should still be improved, because that function did some weird things :). @Maxvanhattum

**Review by niraymak — APPROVED** [review]
Great job! I tested it with the frontend, everything seems to work fine and much faster.
Also tested the .Load() and it did make the endpoint slower, so I think we should leave it like this! 🥇

**Review by Maxvanhattum — APPROVED** [review]
Nice work, this is indeed the cleaner way to code it and you showed that it improved response times!

**Pull request merged**
